<a href="https://colab.research.google.com/github/andyotani/Machine-learning_26-27/blob/main/JS06/Tugas_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tugas Lab

  1.	Buatlah model SVM dengan menggunakan data voice.csv dengan ketentuan,
    1.	Split data dengan rasio 70:30 dan 80:20 untuk setiap model yang akan dibangun.
          1.	Gunakan model dengan kernel linier.
          2.	Gunakan model dengan kernel polynomial.
          3.	Gunakan model dengan kernel RBF.
    2.	Tabulasikan performansi setiap split dan kernel berdasarkan metrik akurasi.

In [ ]:
# 1.1 Model SVM dengan Kernel Linier

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# Membaca data
df = pd.read_csv('voice.csv')

# Memisahkan fitur dan label
X = df.drop(columns=['label'])
y = df['label']

# Mengubah label menjadi numerik
y = y.map({'male': 0, 'female': 1})

# Split 70:30
X_train_70, X_test_70, y_train_70, y_test_70 = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

# Model SVM Linear
svm_linear_70 = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='linear'))
])

svm_linear_70.fit(X_train_70, y_train_70)

# Prediksi
y_pred_linear_70 = svm_linear_70.predict(X_test_70)

# Akurasi
accuracy_linear_70 = accuracy_score(y_test_70, y_pred_linear_70)

print("Akurasi Linear 70:30 =", accuracy_linear_70)

Akurasi Linear 70:30 = 0.9695057833859095

In [ ]:
# 1.1 Model SVM dengan Kernel Linier - Split 80:20

X_train_80, X_test_80, y_train_80, y_test_80 = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

svm_linear_80 = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='linear'))
])

svm_linear_80.fit(X_train_80, y_train_80)

y_pred_linear_80 = svm_linear_80.predict(X_test_80)

accuracy_linear_80 = accuracy_score(y_test_80, y_pred_linear_80)

print("Akurasi Linear 80:20 =", accuracy_linear_80)

Akurasi Linear 80:20 = 0.9684542586750788

In [ ]:
# 1.2 Model SVM dengan Kernel Polynomial

# Split 70:30
X_train_70, X_test_70, y_train_70, y_test_70 = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

# Model SVM Polynomial
svm_poly_70 = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='poly'))
])

svm_poly_70.fit(X_train_70, y_train_70)

# Prediksi
y_pred_poly_70 = svm_poly_70.predict(X_test_70)

# Akurasi
accuracy_poly_70 = accuracy_score(y_test_70, y_pred_poly_70)

print("Akurasi Polynomial 70:30 =", accuracy_poly_70)

Akurasi Polynomial 70:30 = 0.9495268138801262

In [ ]:
# 1.2 Model SVM dengan Kernel Polynomial - Split 80:20

X_train_80, X_test_80, y_train_80, y_test_80 = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

svm_poly_80 = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='poly'))
])

svm_poly_80.fit(X_train_80, y_train_80)

y_pred_poly_80 = svm_poly_80.predict(X_test_80)

accuracy_poly_80 = accuracy_score(y_test_80, y_pred_poly_80)

print("Akurasi Polynomial 80:20 =", accuracy_poly_80)

Akurasi Polynomial 80:20 = 0.9526813880126183

In [ ]:
# 1.3 Model SVM dengan Kernel RBF

# Split 70:30
X_train_70, X_test_70, y_train_70, y_test_70 = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

# Model SVM RBF
svm_rbf_70 = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='rbf'))
])

svm_rbf_70.fit(X_train_70, y_train_70)

# Prediksi
y_pred_rbf_70 = svm_rbf_70.predict(X_test_70)

# Akurasi
accuracy_rbf_70 = accuracy_score(y_test_70, y_pred_rbf_70)

print("Akurasi RBF 70:30 =", accuracy_rbf_70)

Akurasi RBF 70:30 = 0.9810725552050473

In [ ]:
# 1.3 Model SVM dengan Kernel RBF - Split 80:20

X_train_80, X_test_80, y_train_80, y_test_80 = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

svm_rbf_80 = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='rbf'))
])

svm_rbf_80.fit(X_train_80, y_train_80)

y_pred_rbf_80 = svm_rbf_80.predict(X_test_80)

accuracy_rbf_80 = accuracy_score(y_test_80, y_pred_rbf_80)

print("Akurasi RBF 80:20 =", accuracy_rbf_80)

Akurasi RBF 80:20 = 0.9794952681388013

In [ ]:
# 2. Tabulasi Performansi Setiap Split dan Kernel

hasil = pd.DataFrame({
    'Split Data': [
        '70:30',
        '70:30',
        '70:30',
        '80:20',
        '80:20',
        '80:20'
    ],
    'Kernel': [
        'Linear',
        'Polynomial',
        'RBF',
        'Linear',
        'Polynomial',
        'RBF'
    ],
    'Accuracy (%)': [
        accuracy_linear_70 * 100,
        accuracy_poly_70 * 100,
        accuracy_rbf_70 * 100,
        accuracy_linear_80 * 100,
        accuracy_poly_80 * 100,
        accuracy_rbf_80 * 100
    ]
})

hasil['Accuracy (%)'] = hasil['Accuracy (%)'].round(2)

display(hasil)

  Split Data      Kernel  Accuracy (%)
0      70:30      Linear         96.95
1      70:30  Polynomial         94.95
2      70:30         RBF         98.11
3      80:20      Linear         96.85
4      80:20  Polynomial         95.27
5      80:20         RBF         97.95

2.	Gunakan data pada praktikum 5 untuk membuat model klasifikasi siang dan malam menggunakan SVM dengan kernel RBF menggunakan fitur histrogram. Gunakan rasio 80:20. Anda dapat bereksperimen dengan hyperparameter tunning dari kernel RBF. Catat performansi akurasinya!

In [ ]:
import zipfile
with zipfile.ZipFile('images.zip', 'r') as zip_ref:
    zip_ref.extractall('.')

In [ ]:
# IMPORT LIBRARY

from pathlib import Path
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

import cv2
import numpy as np
import pandas as pd
import os


from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import GridSearchCV

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
# DIRECTORY DATASET

train_dir = "images/training/"
test_dir = "images/test/"


print(os.listdir(train_dir))
print(os.listdir(test_dir))

['day', 'night']
['day', 'night']

In [ ]:
# LOAD DATASET


def load_dataset(img_dir):

    img_list = []

    path = Path(img_dir)

    for folder in path.glob("*"):

        label = folder.name


        for file in folder.glob("*.jpg"):

            img = mpimg.imread(file)


            img_list.append(
                (
                    img,
                    label
                )
            )


    return img_list

In [ ]:
# Load gambar
train_img = load_dataset(train_dir)
test_img = load_dataset(test_dir)


print("Jumlah data training :", len(train_img))
print("Jumlah data testing  :", len(test_img))

Jumlah data training : 240
Jumlah data testing  : 160

In [ ]:
# PREPROCESSING

def standarized_input(image):

    img = cv2.resize(
        image,
        (1100,600)
    )

    return img



def label_encoder(label):

    if label == "day":
        return 1

    else:
        return 0



def preprocess(img_list):

    output = []


    for item in img_list:

        image = item[0]
        label = item[1]


        image = standarized_input(image)

        label = label_encoder(label)


        output.append(
            (
                image,
                label
            )
        )


    return output

In [ ]:
train_std_img_list = preprocess(train_img)

test_std_img_list = preprocess(test_img)


print(train_std_img_list[0][0].shape)
print(train_std_img_list[0][1])

(600, 1100, 3)
1

In [ ]:
# FEATURE EXTRACTION HISTOGRAM


def extract_histogram_feature(img_list):

    features = []
    labels = []


    for item in img_list:

        image = item[0]
        label = item[1]


        # RGB ke grayscale

        gray = cv2.cvtColor(
            image,
            cv2.COLOR_RGB2GRAY
        )


        # Histogram

        hist = cv2.calcHist(
            [gray],
            [0],
            None,
            [256],
            [0,256]
        )


        # Normalisasi

        hist = cv2.normalize(
            hist,
            hist
        )


        hist = hist.flatten()


        features.append(hist)

        labels.append(label)



    return np.array(features), np.array(labels)

In [ ]:
# FEATURE TRAINING DAN TESTING

X_train, y_train = extract_histogram_feature(
    train_std_img_list
)


X_test, y_test = extract_histogram_feature(
    test_std_img_list
)


print("Training feature :", X_train.shape)
print("Testing feature  :", X_test.shape)

Training feature : (240, 256)
Testing feature  : (160, 256)

In [ ]:
# SVM RBF DEFAULT


model_rbf = Pipeline([

    (
        "scaler",
        StandardScaler()
    ),

    (
        "svm",
        SVC(
            kernel="rbf"
        )
    )

])


# Training

model_rbf.fit(
    X_train,
    y_train
)

Pipeline(steps=[('scaler', StandardScaler()), ('svm', SVC())])

In [ ]:
# EVALUASI MODEL AWAL


y_pred = model_rbf.predict(
    X_test
)


accuracy_default = accuracy_score(
    y_test,
    y_pred
)


print(
    "Accuracy SVM RBF Default :",
    accuracy_default*100,
    "%"
)

Accuracy SVM RBF Default : 96.25 %

In [ ]:
# HYPERPARAMETER TUNING


param_grid = {


    "svm__C":[
        0.1,
        1,
        10,
        100
    ],


    "svm__gamma":[
        "scale",
        0.001,
        0.01,
        0.1
    ]

}



grid = GridSearchCV(

    model_rbf,

    param_grid,

    cv=5,

    scoring="accuracy",

    n_jobs=-1

)



grid.fit(
    X_train,
    y_train
)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svm', SVC())]),
             n_jobs=-1,
             param_grid={'svm__C': [0.1, 1, 10, 100],
                         'svm__gamma': ['scale', 0.001, 0.01, 0.1]},
             scoring='accuracy')

In [ ]:
# HASIL TUNING


print(
    "Best Parameter:"
)

print(
    grid.best_params_
)


print(
    "\nBest CV Accuracy:"
)

print(
    grid.best_score_*100,
    "%"
)

Best Parameter:
{'svm__C': 10, 'svm__gamma': 0.001}

Best CV Accuracy:
100.0 %

In [ ]:
# TEST MODEL TERBAIK


best_model = grid.best_estimator_


y_pred_best = best_model.predict(
    X_test
)


accuracy_tuned = accuracy_score(
    y_test,
    y_pred_best
)


print(
    "Accuracy Setelah Tuning:",
    accuracy_tuned*100,
    "%"
)

Accuracy Setelah Tuning: 96.25 %

In [ ]:
# CONFUSION MATRIX


cm = confusion_matrix(
    y_test,
    y_pred_best
)


print(cm)

[[77  3]
 [ 3 77]]

In [ ]:
# TABEL PERFORMANSI


result = pd.DataFrame({

    "Model":[
        "SVM RBF Default",
        "SVM RBF Tuned"
    ],


    "Feature":[
        "Histogram",
        "Histogram"
    ],


    "Kernel":[
        "RBF",
        "RBF"
    ],


    "Accuracy (%)":[

        accuracy_default*100,

        accuracy_tuned*100

    ]

})


result["Accuracy (%)"] = (
    result["Accuracy (%)"]
    .round(2)
)


result

             Model    Feature Kernel  Accuracy (%)
0  SVM RBF Default  Histogram    RBF         96.25
1    SVM RBF Tuned  Histogram    RBF         96.25